spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC&characterEncoding=UTF-8
