spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin
    username: ${USERNAME}
    password: ${PASSOWRD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create