spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

aws:
   ses:
    access-key: ${MAIL_ACCESS}
    secret-key: ${MAIL_SECRET}
