

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: dlgktjd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
server:
  port: 1234