spring:
  # DB 설정
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver #driver 설정인데 cj가 최신거라 cj붙여야함

  jpa:
    show-sql: true # jpa가 보내는 쿼리를 보여줘요
    properties:
      hibernate:
        format_sql: true #