spring:
  # DB ?? ??
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver #driver ? cj ???? ?????? ???? ?????

  jpa:
    show-sql: true # jpa? ??? ?? ?? clr? ???
    properties:
      hibernate:
        format_sql: true # ???? ??? ??? ??