spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:11111111}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:practicedb}?serverTimezone=UTC&characterEncoding=UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE
