spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
